### PR TITLE
migrated NotificationSettings fragment to NotificationSettingsScreen Composable 

### LINKED ISSUE #175: Migrate Notification Settings feature to Jetpack Compose
Currently feature Account in `presentation/notificationsettings` package is implemented with XML view system. Let's convert it to Jetpack Compose. See `shop` feature for reference

### PR DESCRIPTION
**Pull request by Yashraj254**
> ## NotificationSettings in Jetpack Compose (Fixes #175 )
> * [x]  Implemented NotificationSettings Screen Composable
> * [x]  Deleted fragment_notification_settings.xml file

> ## Screenshot
> Screenshot_2023-10-04-04-28-01-43_4c7a1d9749c5968f7f9bd1b0ef18adf7 1

### CODE REVIEW

**Comment by Yashraj254** [comment]
hey @hieuwu , though this should work as expected, i am facing problems with authentication part as it keeps giving me request time out error, also my email rate limit is exceeded, i am unable to test it properly. it will be helpful if you can take a look at it.

**Comment by hieuwu** [comment]
> hey @hieuwu , though this should work as expected, i am facing problems with authentication part as it keeps giving me request time out error, also my email rate limit is exceeded, i am unable to test it properly. it will be helpful if you can take a look at it.

Great work Yash. I’ll take a look and test it. No worries

**Comment by Yashraj254** [comment]
@hieuwu thanks.😊

**Review by hieuwu — APPROVED** [review]

**Comment by hieuwu** [comment]
Hi just a question @Yashraj254 . Did you create account on Supabase?

**Comment by Yashraj254** [comment]
@hieuwu yes i did.

**Pull request merged**
