### PR TITLE
Migrate onboarding feature from XML to Jetpack Compose

### LINKED ISSUE #124: Use HiltViewModel to provide ViewModels
**Is your feature request related to a problem? Please describe.**
Use HiltViewModel to provide ViewModels to avoid boilerplate code

**Describe the solution you'd like**
Use HiltViewModel

**Describe alternatives you've considered**
None

### LINKED ISSUE #176: Migrate onboarding to Jetpack Compose
Currently feature Account in `presentation/onboarding` package is implemented with XML view system. Let's convert it to Jetpack Compose. See `shop` feature for reference

### PR DESCRIPTION
**Pull request by Devendra34**
## Onboarding in Jetpack Compose (Fixes #176)
- [x] Implemented OnboardingScreen Composable
- [x] Deleted activity_onboarding.xml file

## Composable tree

- `OnboardingScreen` (Box)
  - `OnboardingScreenBackground` (Image bg)
  - `OnboardingScreenContent` (Column with bottom alignment)
      - Carrot logo (Image)
      - Welcome text 1 (Text)
      - Welcome text 2 (Text)
      - Get Started (PrimaryButton)

## Core widgets
- [x] PrimaryButton
- [x] SecondaryButton

#### Onboarding
Screenshot_20231001_160508

#### PrimaryButton
Ignore Preview layout bounds of blue color
ezgif com-video-to-gif

### CODE REVIEW

**Comment by hieuwu** [comment]
Hi @Devendra34 , would you mind updating some screenshot? It would be easier for me to review the change. Thanks a lot

**Comment by Devendra34** [comment]
Sure @hieuwu,
Updated the PR description with screenshot.
Since there was no visual UI change, I was unsure whether to include it or not.

**Comment by hieuwu** [comment]
Looks good to me. Feel free to raise anything you want to add to the project @Devendra34 . Thank you so much for your contribution ! 👍

**Comment by Devendra34** [comment]
> Looks good to me. Feel free to raise anything you want to add to the project @Devendra34 . Thank you so much for your contribution ! 👍

Thank you @hieuwu. 
I you like my work, I'm happy to contribute for other Compose issues as well. Requested #173 as of now.

**Pull request merged**
