### PR TITLE
Upgrade Gradle Version

### PR DESCRIPTION
**Pull request by Raghu1124**
I had upgraded the gradle version to the current version of 8.4, and let me know if I can work on any other issue.

### CODE REVIEW

**Comment by Raghu1124** [comment]
> I had upgraded the gradle version to the current version of 8.4, and let me know if I can work on any other issue.

plz let me know if their was any error in my PR

**Review by hieuwu — APPROVED** [review]

**Comment by Raghu1124** [comment]
@hieuwu , Sorry for that PR,  I think their might be some issue during the gradle biuild, can I work on it again. please assign it to me again

**Comment by hieuwu** [comment]
> @hieuwu , Sorry for that PR, I think their might be some issue during the gradle biuild, can I work on it again. please assign it to me again

It's already yours. Please continue working on it and push to this PR

**Comment by Raghu1124** [comment]
I had deleted this repo by mistake but forked it again, does it matter in my PR?

**Comment by Raghu1124** [comment]
> I had deleted this repo by mistake but forked it again, does it matter in my PR?

I want to send the new PR, should i send it or you will assign it again

**Comment by Raghu1124** [comment]
@hieuwu please assign me this issue again, I want to send the PR

> > I had deleted this repo by mistake but forked it again, does it matter in my PR?
> 
> I want to send the new PR, should i send it or you will assign it again

**Comment by hieuwu** [comment]
You are already assigned. It still counts, don't worry about it.
*Vũ Hoàng Hiếu*


Vào Th 4, 11 thg 10, 2023 vào lúc 03:17 Raghunandan Bansal <
***@***.***> đã viết:

**Pull request closed without merging**
