### PR TITLE
Added transition effect to product detail

### PR DESCRIPTION
**Pull request by AmartyaSingh97**
Added animation and transition files under res/anim and res/transition section which can be used later anywhere in the app.
Used slide right and fade transition effect into product details while entering and exiting the fragment respectively.

### CODE REVIEW

**Comment by hieuwu** [comment]
It would be great if you add screenshort or video of the result

**Comment by AmartyaSingh97** [comment]
https://user-images.githubusercontent.com/85061899/193420554-3beb8d86-6efc-455a-adb8-5a6a2558ac6a.mp4

**Review by hieuwu — APPROVED** [review]
LGTM!

**Comment by AmartyaSingh97** [comment]
@hieuwu Please reopen the PR, it was accidently closed by me !!

**Comment by hieuwu** [comment]
HI I checked again. All the commits of this PR ahs been merged to main branch. So that we can not reopen this PR. Still marked as accepted but not sure Hacktofest will accept this

**Pull request closed without merging**
